---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: netrouse

builds:
  - id: cli
    binary: "{{ .ProjectName }}"
    main: ./cmd/cli
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s
    env:
      - CGO_ENABLED=0

archives:
  - id: binary
    ids:
      - cli
    formats: ["binary"]

changelog:
  disable: true
release:
  disable: true
