#!/bin/bash

set -e

base_dir="$(dirname "${BASH_SOURCE[0]}" | xargs realpath | xargs dirname)"

# shellcheck source=common.sh
source "${base_dir}/hack/common.sh"

if [ ! -d "${HOME}/.cache" ]; then
    mkdir "${HOME}/.cache"
fi

podman run -t --rm \
    --name netrouse-builder \
    -v "${base_dir}:/app:z" \
    -v "${HOME}/.cache":/root/.cache:z \
    "${BUILDER_IMAGE}" \
    "$@"
