Website = "https://github.com/heathcliff26/netrouse"

[Details]
Icon = "../../packages/io.github.heathcliff26.netrouse.png"
Name = "NetRouse"
ID = "io.github.heathcliff26.netrouse"
Version = "${gui_version}"
Build = 0

[Migrations]
fyneDo = true

[AdaptiveIcon]
Foreground = "tools/android-icon.png"
